<?php
/**
 * @category Emailpreview
 * @package Titechde_Emailpreview
 * @authors TiTech <info@titechnologies.in, http://www.titechnologies.de/>
 * @developer TiTech <info@titechnologies.in, http://www.titechnologies.de/>
 * @version 1.0.0
 * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<style>
body {
    color: #2f2f2f;
    font: 12px/1.5em Arial,Helvetica,sans-serif;
    width:100%;
}
</style>
<?php echo $this->getChildHtml('content') ?>
